print (3 + 4)
print (3 - 4)
print (3 * 4)
print (3 % 4)
print (3 / 4)
print (3 ** 4)
print (3 // 4)
print ("Manin Farid")
print ("ALI DAOUDA")
print ('BENIN')
print ('I am enjoying 30 days of python')
print (type(10))
print(type(9.8))
print(type(3.14))
print(type(4 - 4j))
print(type(['Asabeneh', 'Python', 'Finland']))
print(type("Manin Farid"))
print(type(" ALI DAOUDA"))
print(type('BENIN'))
print(type(True))
print(type(("Lemon", "Orange", "John")))
print(type({1,4,'lord', 10}))
print(type({'first name': 'ALI DAOUDA', 'last name': 'Manin Farid', 'single':True}))